"""Danh sách các key bắt buộc trong YAML config.

Khi thêm tham số mới, khai báo ở đây để bắt thiếu sót sớm ở `load_config`.
"""

REQUIRED_KEYS: tuple[str, ...] = (
    # paths
    "paths.ref_image",
    "paths.deformed_image",
    "paths.calib_file",
    "paths.output_dir",
    "paths.calib_dir",
    "paths.batch_output_subdir",
    # camera
    "camera.device_id",
    "camera.warmup_frames",
    # calibration
    "calibration.checkerboard_size",
    "calibration.square_size",
    "calibration.criteria.max_iter",
    "calibration.criteria.eps",
    "calibration.subpix_window",
    # preprocessing
    "preprocessing.blur_kernel",
    "preprocessing.clahe_clip_limit",
    "preprocessing.clahe_grid",
    # detection
    "detection.min_threshold",
    "detection.max_threshold",
    "detection.step",
    "detection.min_area",
    "detection.max_area",
    "detection.min_circularity",
    "detection.min_inertia",
    "detection.min_convexity",
    # tracking
    "tracking.min_displacement",
    "tracking.pyrlk.win_size",
    "tracking.pyrlk.max_level",
    "tracking.pyrlk.fb_threshold",
    "tracking.pyrlk.term_criteria.max_iter",
    "tracking.pyrlk.term_criteria.eps",
    # slip v1
    "slip_detection.slip_threshold",
    "slip_detection.min_motion_thresh",
    "slip_detection.min_moving_markers",
    "slip_detection.alpha",
    "slip_detection.alpha_decay",
    "slip_detection.rebound_dot_prod_threshold",
    "slip_detection.press_rate_threshold",
    "slip_detection.history_buffer_length",
    "slip_detection.moving_count_thresh",
    # slip v2
    "slip_v2.scales",
    "slip_v2.min_valid_markers",
    "slip_v2.translation_norm",
    "slip_v2.translation_min",
    "slip_v2.short_gate_norm",
    "slip_v2.short_gate_softmin",
    "slip_v2.short_gate_max_scale",
    "slip_v2.coherence_min",
    "slip_v2.score_on",
    "slip_v2.score_off",
    "slip_v2.alpha_up",
    "slip_v2.alpha_down",
    "slip_v2.radial_rate_min",
    "slip_v2.press_slip_ratio",
    # visualization base
    "visualization.arrow_scale",
    "visualization.arrow_non_moving_color",
    "visualization.arrow_thickness",
    "visualization.arrow_tip_length",
    "visualization.start_marker_color",
    "visualization.keypoint_color",
    "visualization.motion_magnitude_threshold",
    "visualization.color_intensity_multiplier",
    "visualization.summary_figsize",
    "visualization.summary_dpi",
    # visualization text
    "visualization.text.status_pos",
    "visualization.text.fps_pos",
    "visualization.text.slip_pos",
    "visualization.text.timing_start_y",
    "visualization.text.timing_step_y",
    "visualization.text.scale_normal",
    "visualization.text.scale_idle",
    "visualization.text.thickness",
    "visualization.text.color_tracking",
    "visualization.text.color_idle",
    "visualization.text.color_slip",
    "visualization.text.color_moving",
    "visualization.text.color_timing",
    # overlay v2
    "visualization.overlay_v2.font_scale_main",
    "visualization.overlay_v2.font_scale_detail",
    "visualization.overlay_v2.font_scale_perf",
    "visualization.overlay_v2.font_scale_idle",
    "visualization.overlay_v2.font_scale_idle_fps",
    "visualization.overlay_v2.main_pos",
    "visualization.overlay_v2.detail_pos",
    "visualization.overlay_v2.perf_pos",
    "visualization.overlay_v2.idle_main_pos",
    "visualization.overlay_v2.idle_fps_pos",
    "visualization.overlay_v2.perf_color",
    "visualization.overlay_v2.idle_color",
    "visualization.overlay_v2.idle_fps_color",
    "visualization.overlay_v2.phase_colors.slip",
    "visualization.overlay_v2.phase_colors.pressing",
    "visualization.overlay_v2.phase_colors.releasing",
    "visualization.overlay_v2.phase_colors.alert",
    "visualization.overlay_v2.phase_colors.tracking",
    "visualization.overlay_v2.hud_arrow.offset_x_from_right",
    "visualization.overlay_v2.hud_arrow.offset_y_from_bottom",
    "visualization.overlay_v2.hud_arrow.scale",
    "visualization.overlay_v2.hud_arrow.center_radius",
    "visualization.overlay_v2.hud_arrow.center_color",
    "visualization.overlay_v2.hud_arrow.min_magnitude",
    "visualization.overlay_v2.hud_arrow.thickness",
    "visualization.overlay_v2.hud_arrow.tip_length",
    "visualization.overlay_v2.slip_bar.margin_x",
    "visualization.overlay_v2.slip_bar.margin_y_from_bottom",
    "visualization.overlay_v2.slip_bar.width",
    "visualization.overlay_v2.slip_bar.height",
    "visualization.overlay_v2.slip_bar.bg_color",
    "visualization.overlay_v2.slip_bar.threshold_on_color",
    "visualization.overlay_v2.slip_bar.threshold_off_color",
    # controls
    "controls.wait_key",
    "controls.key_capture",
    "controls.key_clear",
    "controls.key_quit",
    # pipeline
    "pipeline.use_calibration",
)
